// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  define(['backbone', 'router/router'], function(Backbone, AppRouter) {
    new AppRouter();
    return Backbone.history.start();
  });

}).call(this);
