// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  define(['collection/people', 'data/users'], function(AppCollectionPeople, AppDataUsers) {
    return new AppCollectionPeople(AppDataUsers);
  });

}).call(this);
