// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  define(['backbone', 'model/user'], function(Backbone, AppModelUser) {
    return Backbone.Collection.extend({
      model: AppModelUser
    });
  });

}).call(this);
