// Generated by CoffeeScript 1.6.2
define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  'use strict';  return Backbone.View.extend({
    id: 'page404',
    template: _.template($('#page404Template').html()),
    render: function() {
      return $('body').html(this.template());
    }
  });
});
