// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    return Backbone.View.extend({
      id: 'page404',
      template: _.template($('#page404Template').html()),
      render: function() {
        return $('body').html(this.template());
      }
    });
  });

}).call(this);
