// Generated by CoffeeScript 1.6.2
define(['jquery', 'underscore', 'backbone', 'view/user'], function($, _, Backbone, AppUserView) {
  'use strict';  return Backbone.View.extend({
    tagName: 'ul',
    id: 'userList',
    initialize: function() {
      return Backbone.on('deselect:all', this.deSelectAll, this);
    },
    render: function() {
      this.collection.each(function(userModel) {
        var userView;

        userView = new AppUserView({
          model: userModel
        });
        return this.$el.append(userView.el);
      }, this);
      return this;
    },
    deSelectAll: function() {
      return this.$('.selected').removeClass('selected');
    }
  });
});
