// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'underscore', 'backbone', 'view/user'], function($, _, Backbone, AppUserView) {
  'use strict';
  var View, _ref;

  return View = (function(_super) {
    __extends(View, _super);

    function View() {
      _ref = View.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    View.prototype.tagName = 'ul';

    View.prototype.id = 'userList';

    View.prototype.initialize = function() {
      return Backbone.on('deselect:all', this.deSelectAll, this);
    };

    View.prototype.render = function() {
      this.collection.each(function(userModel) {
        var userView;

        userView = new AppUserView({
          model: userModel
        });
        return this.$el.append(userView.el);
      }, this);
      return this;
    };

    View.prototype.deSelectAll = function() {
      return this.$('.selected').removeClass('selected');
    };

    return View;

  })(Backbone.View);
});
