// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
  'use strict';
  var View, _ref;

  return View = (function(_super) {
    __extends(View, _super);

    function View() {
      _ref = View.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    View.prototype.tagName = 'li';

    View.prototype.template = _.template($('#userTemplate').html());

    View.prototype.initialize = function() {
      this.render();
      this.listenTo(this.model, 'change:name', this.render, this);
      return this.listenTo(this.model, 'select:current', this.select, this);
    };

    View.prototype.render = function() {
      this.$el.html(this.template({
        data: this.model.toJSON()
      }));
      return this;
    };

    View.prototype.select = function() {
      return this.$el.addClass('selected');
    };

    return View;

  })(Backbone.View);
});
