// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone'], function(Backbone) {
  'use strict';
  var Model, _ref;

  return Model = (function(_super) {
    __extends(Model, _super);

    function Model() {
      _ref = Model.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Model.prototype.defaults = {
      sex: 'Мужской'
    };

    Model.prototype.validate = function(attrs) {
      var errors;

      errors = [];
      if (!/^[А-Яа-я]{1,}$/.test(attrs.name)) {
        errors.push('Введите свое имя кириллицей!');
      }
      if (attrs.age < 10 || attrs.age > 100) {
        errors.push('Введите цифрами Ваш реальный возраст!');
      }
      if (!/^[А-Яа-я]{1,}$/.test(attrs.job)) {
        errors.push('Введите профессию кириллицей!');
      }
      if (attrs.sex !== 'Мужской' && attrs.sex !== 'Женский') {
        errors.push('Выберите правильно пол!');
      }
      if (errors.length) {
        return errors;
      }
    };

    return Model;

  })(Backbone.Model);
});
